import './globals.css'
import { Oswald } from 'next/font/google';
 
const oswald = Oswald({
  weight: '700',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Spotify: Your Top Artists',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={oswald.className}>
        <header>
            Spotify Stats
        </header>
        {children}
        </body>
    </html>
  )
}
