import Link from 'next/link';
import './globals.css'
import { Oswald } from 'next/font/google';
import SpotifyImg from '../public/spotify.svg'
import Image from 'next/image';


const oswald = Oswald({
  weight: '700',
  subsets: ['latin'],
});

export const metadata = {
  title: 'Spotify: Your Top Artists',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={oswald.className}>
        <header>
            <Link href="https://spotify.com" target='_blank'>
              <Image src={SpotifyImg}  alt='spotify' height={30} width={30}/>
            </Link>
            <Link href="/">Spotify Stats</Link> 
        </header>
        {children}
        </body>
    </html>
  )
}
